#!/bin/zsh
# Wrapper for sendElro (433 Mhz)
# License: WTFPL

usage() {
    echo "Usage: $1 [ID] [on|off]"
    echo "ID: Integer (0-3). If not provided, on|off gets broadcasted"
    exit 0 
}

lamp() {
    local i=$(echo "2^$1" | bc -l)
    local cmd="pilight-send -p elro -s 1 -u"
    cmd="${cmd} $i"
    [[ "$2" == "on" ]] && cmd="${cmd} -t" || cmd="${cmd} -f"
    eval $cmd
}

# Lamp on/off
lon() {
    for l in 1 2 3 4; do
        lamp 1 on
    done
}

loff() {
    for l in 1 2 3 4; do
        lamp 1 off
    done
}

case $# in
    1)
        # Broadcast
        [[ "$1" == "on" ]] && lon || loff
        ;;
    2)
        # Selectively turn one lamp on or off
        lamp $1 $2
        ;;
    *)
        usage $(basename $0)
        ;;
esac

