#!/bin/zsh
# Wrapper for sendElro (433 Mhz)
# License: WTFPL

usage() {
    echo "Usage: $1 [ID] [on|off]"
    echo "ID: Integer (0-3). If not provided, on|off gets broadcasted"
    exit 0 
}

lamp() {
    local i=$(echo "2^$1" | bc -l)
    local cmd="pilight-send -p elro -s 1 -u"
    cmd="${cmd} $i"
    [[ "$2" == "on" ]] && cmd="${cmd} -t" || cmd="${cmd} -f"
    echo $cmd
    # TODO: Wouldn't "sudo $cmd" be enough ?
    sudo su -c $cmd
}

# Lamp on/off
lon() {
    sudo su -c "pilight-send -p elro -s 1 -u 1 -t; pilight-send -p elro -s 1 -u 2 -t; pilight-send -p elro -s 1 -u 4 -t; pilight-send -p elro -s 1 -u 8 -t"
}

loff() {
    sudo su -c "pilight-send -p elro -s 1 -u 1 -f; pilight-send -p elro -s 1 -u 2 -f; pilight-send -p elro -s 1 -u 4 -f; pilight-send -p elro -s 1 -u 8 -f"
}

case $# in
    1)
        # Broadcast
        [[ "$1" == "on" ]] && lon || loff
        ;;
    2)
        # Selectively turn one lamp on or off
        lamp $1 $2
        ;;
    *)
        usage $(basename $0)
        ;;
esac

