#!/usr/bin/env sh

#HOST=alarmpi
#WATCHDIR=/mnt/alarmpi/home/dl/torrents/.watchdir
HOST=localhost
WATCHDIR=/home/pschmitt/downloads/torrents/.watchdir

if [[ "$HOST" == "localhost" ]];then
    pidof -o %PPID /usr/bin/transmission-daemon > /dev/null 2>&1 || { zenity --error --text "transmission-daemon not running \!" 2>/dev/null; exit 1; }
fi    
transmission-remote $HOST -a "$1" || echo "$1" > "$WATCHDIR/$(date +%s).torrent"
[[ $? -eq 0 ]] && zenity --warning --text "Successfully added torrent \! ($HOST)" 2>/dev/null || zenity --error 2>/dev/null

